#!/bin/bash

internal="eDP1"
external="HDMI1"

if [ "$(xrandr | grep "$external" | awk '{print $2}')" == "disconnected" ]; then
		xrandr --output $internal --auto &&
		dunstify -t 1000 -r 10 -i dialog-information "$external disconnected"
		canberra-gtk-play -i dialog-information
		exit 1
fi

dmenufont="monospace:size=10"
list=("Clone\nInternal\nExternal\nExtended right\nExtended left\nExtended above")
choice=$(echo -e "$list" | dmenu -fn "$dmenufont")


case "$choice" in
	"Clone")
		xrandr --output $internal --auto --output $external --auto --same-as $internal &&
		dunstify -t 1000 -r 10 -i dialog-information "Display Clone"
		canberra-gtk-play -i dialog-information
		;;
	"Internal")
		xrandr --output $internal --auto --output $external --off &&
		dunstify -t 1000 -r 10 -i dialog-information "Display Internal"
		canberra-gtk-play -i dialog-information
		;;
	"External")
		xrandr --output $internal --off --output $external --auto &&
		dunstify -t 1000 -r 10 -i dialog-information "Display External"
		canberra-gtk-play -i dialog-information
		;;
	"Extended right")
		xrandr --output $internal --auto --primary --output $external --auto --right-of $internal &&
		dunstify -t 1000 -r 10 -i dialog-information "Display Extended Right"
		canberra-gtk-play -i dialog-information
		;;
	"Extended left")
		xrandr --output $internal --auto --primary --output $external --auto --left-of $internal &&
		dunstify -t 1000 -r 10 -i dialog-information "Display Extended Left"
		canberra-gtk-play -i dialog-information
		;;
	"Extended above")
		xrandr --output $internal --auto --primary --output $external --auto --above $internal &&
		dunstify -t 1000 -r 10 -i dialog-information "Display Extended Above"
		canberra-gtk-play -i dialog-information
		;;
esac
