#!/bin/bash

wallpaper="$(cat ~/.fehbg | grep feh | awk '{print $4}' | sed 's/\x27//g')"

list=("Apagar\nReiniciar\nSuspender\nCerrar sesión\nBloquear pantalla")
choice=$(echo -e "$list" | dmenu -m 0)

case "$choice" in
	"Apagar")
	   	systemctl poweroff
		;;
	"Reiniciar")
		systemctl reboot
		;;
	"Suspender")
		systemctl suspend
		;;
	"Cerrar sesión")
		loginctl | grep $USER | awk '{print $1}' | xargs loginctl terminate-session
		;;
	"Bloquear pantalla")
		i3lock -nti $wallpaper
		;;
esac
