#!/bin/bash
# renombrar según los identificadores de monitor definidos en /etc/X11/xorg.conf.d/30-monitor.conf
internal="eDP-1"
external="HDMI-1"

if [ "$(xrandr | grep "$external" | awk '{print $2}')" == "disconnected" ]; then
		xrandr --output $internal --auto &&
		echo "$external disconnected" | dmenu
		exit 1
fi

list=("Clone\nInternal\nExternal\nExtended right\nExtended left\nExtended above")
choice=$(echo -e "$list" | dmenu)

case "$choice" in
	"Clone")
		xrandr --output $internal --auto --output $external --auto --same-as $internal &&
		msg="Display Clone"
		;;
	"Internal")
		xrandr --output $internal --auto --output $external --off &&
		msg="Display Internal"
		;;
	"External")
		xrandr --output $internal --off --output $external --auto &&
		msg="Display External"
		;;
	"Extended right")
		xrandr --output $internal --auto --primary --output $external --auto --right-of $internal &&
		msg="Display Extended Right"
		;;
	"Extended left")
		xrandr --output $internal --auto --primary --output $external --auto --left-of $internal &&
		msg="Display Extended Left"
		;;
	"Extended above")
		xrandr --output $internal --auto --primary --output $external --auto --above $internal &&
		msg="Display Extended Above"
		;;
esac

if [ -n "$msg" ]; then
	dunstify -t 1000 -r 10 -i dialog-information "$msg"
	canberra-gtk-play -i dialog-information
fi
