#!/usr/bin/bash

usbdrives=$(lsblk -rpo name,type,size,mountpoint | awk '$2=="part" && $4=="" {printf "%s (%s)\n", $1, $3}')

if [ -z "$usbdrives" ]; then
	echo "Nada que montar" | dmenu
	exit 1
else
	usbdrive=$(echo "$usbdrives" | dmenu)
	if [ $? -eq 1 ]; then
		echo "Operación cancelada."
		exit 1
	else
		device=$(echo $usbdrive | awk '{print $1}')
		usblabel=$(lsblk -no label $device)
		usbsize=$(lsblk -no size $device)
		output="$(udisksctl mount -b $usbdrive)"
		if [ $? -eq 1 ]; then
			dunstify "Error al montar $device"
			exit 1
		else
			mp=$(echo $output | awk -F " at " '{print $2}')
			dunstify "Device $device" "mounted at $mp"
			exit 0
		fi
	fi
fi
